### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Psykka** [Psykka/NESZ#1]
- [ ] Write decent README
- [ ] CPU
  - [ ] Finish 6502 instruction set
  - [ ] Finish all test cases
- [ ] PPU
- [ ] APU
- [ ] Create frontend app
  - [ ] Input mapper
  - [ ] OpenGL render
  - [ ] Maybe another render method
- [x] Parse all functions and variable names to camelCase
- [ ] Build workflow
  - [x] Replace cmake to meson
  - [x] Single file for all build tasks
  - [x] Linux
  - [x] Windows
  - [x] OSX
  - [ ] OS matrix for build
